@echo off
  AMIDEWINx64.EXE /SM "SLIMBOOK"
  AMIDEWINx64.EXE /SP "PROX15-AMD"
  AMIDEWINx64.EXE /SF "RENOIR"
  AMIDEWINx64.EXE /SK "0001"
  AMIDEWINx64.EXE /BM "SLIMBOOK"
  AMIDEWINx64.EXE /BP "PROX15-AMD"
  AMIDEWINx64.EXE /CM "SLIMBOOK"
